namespace AvaloniaNES.Device.CPU;

public partial class Olc6502
{
    private struct Instruction
    {
        public string Name;
        public AddressingMode AddrMode;
        public Func<byte> Operation;
        public byte Cycles;
    }
    private Dictionary<byte, Instruction> instructions = new ();
    
    private byte fetch()
    {
        if (instructions[opcode].AddrMode != IMP)
            fetched = Read(addr_abs);
        return fetched;
    }

    private void InitializeInstructions()
    {
        // this is generated by AI(Deep Seek, this is really Boring)
        instructions.Add(0x00, new Instruction() { Name = "BRK", AddrMode = IMP, Operation = BRK, Cycles = 7 });
        instructions.Add(0x01, new Instruction() { Name = "ORA", AddrMode = IZX, Operation = ORA, Cycles = 6 });
        instructions.Add(0x02, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x03, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 8 });
        instructions.Add(0x04, new Instruction() { Name = "NOP", AddrMode = IMP, Operation = NOP, Cycles = 3 });
        instructions.Add(0x05, new Instruction() { Name = "ORA", AddrMode = ZP0, Operation = ORA, Cycles = 3 });
        instructions.Add(0x06, new Instruction() { Name = "ASL", AddrMode = ZP0, Operation = ASL, Cycles = 5 });
        instructions.Add(0x07, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 5 });
        instructions.Add(0x08, new Instruction() { Name = "PHP", AddrMode = IMP, Operation = PHP, Cycles = 3 });
        instructions.Add(0x09, new Instruction() { Name = "ORA", AddrMode = IMM, Operation = ORA, Cycles = 2 });
        instructions.Add(0x0A, new Instruction() { Name = "ASL", AddrMode = IMP, Operation = ASL, Cycles = 2 });
        instructions.Add(0x0B, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x0C, new Instruction() { Name = "NOP", AddrMode = IMP, Operation = NOP, Cycles = 4 });
        instructions.Add(0x0D, new Instruction() { Name = "ORA", AddrMode = ABS, Operation = ORA, Cycles = 4 });
        instructions.Add(0x0E, new Instruction() { Name = "ASL", AddrMode = ABS, Operation = ASL, Cycles = 6 });
        instructions.Add(0x0F, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });

        instructions.Add(0x10, new Instruction() { Name = "BPL", AddrMode = REL, Operation = BPL, Cycles = 2 });
        instructions.Add(0x11, new Instruction() { Name = "ORA", AddrMode = IZY, Operation = ORA, Cycles = 5 });
        instructions.Add(0x12, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x13, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 8 });
        instructions.Add(0x14, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 4 });
        instructions.Add(0x15, new Instruction() { Name = "ORA", AddrMode = ZPX, Operation = ORA, Cycles = 4 });
        instructions.Add(0x16, new Instruction() { Name = "ASL", AddrMode = ZPX, Operation = ASL, Cycles = 6 });
        instructions.Add(0x17, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });
        instructions.Add(0x18, new Instruction() { Name = "CLC", AddrMode = IMP, Operation = CLC, Cycles = 2 });
        instructions.Add(0x19, new Instruction() { Name = "ORA", AddrMode = ABY, Operation = ORA, Cycles = 4 });
        instructions.Add(0x1A, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 2 });
        instructions.Add(0x1B, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 7 });
        instructions.Add(0x1C, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 4 });
        instructions.Add(0x1D, new Instruction() { Name = "ORA", AddrMode = ABX, Operation = ORA, Cycles = 4 });
        instructions.Add(0x1E, new Instruction() { Name = "ASL", AddrMode = ABX, Operation = ASL, Cycles = 7 });
        instructions.Add(0x1F, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 7 });

        instructions.Add(0x20, new Instruction() { Name = "JSR", AddrMode = ABS, Operation = JSR, Cycles = 6 });
        instructions.Add(0x21, new Instruction() { Name = "AND", AddrMode = IZX, Operation = AND, Cycles = 6 });
        instructions.Add(0x22, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x23, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 8 });
        instructions.Add(0x24, new Instruction() { Name = "BIT", AddrMode = ZP0, Operation = BIT, Cycles = 3 });
        instructions.Add(0x25, new Instruction() { Name = "AND", AddrMode = ZP0, Operation = AND, Cycles = 3 });
        instructions.Add(0x26, new Instruction() { Name = "ROL", AddrMode = ZP0, Operation = ROL, Cycles = 5 });
        instructions.Add(0x27, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 5 });
        instructions.Add(0x28, new Instruction() { Name = "PLP", AddrMode = IMP, Operation = PLP, Cycles = 4 });
        instructions.Add(0x29, new Instruction() { Name = "AND", AddrMode = IMM, Operation = AND, Cycles = 2 });
        instructions.Add(0x2A, new Instruction() { Name = "ROL", AddrMode = IMP, Operation = ROL, Cycles = 2 });
        instructions.Add(0x2B, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x2C, new Instruction() { Name = "BIT", AddrMode = ABS, Operation = BIT, Cycles = 4 });
        instructions.Add(0x2D, new Instruction() { Name = "AND", AddrMode = ABS, Operation = AND, Cycles = 4 });
        instructions.Add(0x2E, new Instruction() { Name = "ROL", AddrMode = ABS, Operation = ROL, Cycles = 6 });
        instructions.Add(0x2F, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });

        instructions.Add(0x30, new Instruction() { Name = "BMI", AddrMode = REL, Operation = BMI, Cycles = 2 });
        instructions.Add(0x31, new Instruction() { Name = "AND", AddrMode = IZY, Operation = AND, Cycles = 5 });
        instructions.Add(0x32, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x33, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 8 });
        instructions.Add(0x34, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 4 });
        instructions.Add(0x35, new Instruction() { Name = "AND", AddrMode = ZPX, Operation = AND, Cycles = 4 });
        instructions.Add(0x36, new Instruction() { Name = "ROL", AddrMode = ZPX, Operation = ROL, Cycles = 6 });
        instructions.Add(0x37, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });
        instructions.Add(0x38, new Instruction() { Name = "SEC", AddrMode = IMP, Operation = SEC, Cycles = 2 });
        instructions.Add(0x39, new Instruction() { Name = "AND", AddrMode = ABY, Operation = AND, Cycles = 4 });
        instructions.Add(0x3A, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 2 });
        instructions.Add(0x3B, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 7 });
        instructions.Add(0x3C, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 4 });
        instructions.Add(0x3D, new Instruction() { Name = "AND", AddrMode = ABX, Operation = AND, Cycles = 4 });
        instructions.Add(0x3E, new Instruction() { Name = "ROL", AddrMode = ABX, Operation = ROL, Cycles = 7 });
        instructions.Add(0x3F, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 7 });

        instructions.Add(0x40, new Instruction() { Name = "RTI", AddrMode = IMP, Operation = RTI, Cycles = 6 });
        instructions.Add(0x41, new Instruction() { Name = "EOR", AddrMode = IZX, Operation = EOR, Cycles = 6 });
        instructions.Add(0x42, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x43, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 8 });
        instructions.Add(0x44, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 3 });
        instructions.Add(0x45, new Instruction() { Name = "EOR", AddrMode = ZP0, Operation = EOR, Cycles = 3 });
        instructions.Add(0x46, new Instruction() { Name = "LSR", AddrMode = ZP0, Operation = LSR, Cycles = 5 });
        instructions.Add(0x47, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 5 });
        instructions.Add(0x48, new Instruction() { Name = "PHA", AddrMode = IMP, Operation = PHA, Cycles = 3 });
        instructions.Add(0x49, new Instruction() { Name = "EOR", AddrMode = IMM, Operation = EOR, Cycles = 2 });
        instructions.Add(0x4A, new Instruction() { Name = "LSR", AddrMode = IMP, Operation = LSR, Cycles = 2 });
        instructions.Add(0x4B, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x4C, new Instruction() { Name = "JMP", AddrMode = ABS, Operation = JMP, Cycles = 3 });
        instructions.Add(0x4D, new Instruction() { Name = "EOR", AddrMode = ABS, Operation = EOR, Cycles = 4 });
        instructions.Add(0x4E, new Instruction() { Name = "LSR", AddrMode = ABS, Operation = LSR, Cycles = 6 });
        instructions.Add(0x4F, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });

        instructions.Add(0x50, new Instruction() { Name = "BVC", AddrMode = REL, Operation = BVC, Cycles = 2 });
        instructions.Add(0x51, new Instruction() { Name = "EOR", AddrMode = IZY, Operation = EOR, Cycles = 5 });
        instructions.Add(0x52, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x53, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 8 });
        instructions.Add(0x54, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 4 });
        instructions.Add(0x55, new Instruction() { Name = "EOR", AddrMode = ZPX, Operation = EOR, Cycles = 4 });
        instructions.Add(0x56, new Instruction() { Name = "LSR", AddrMode = ZPX, Operation = LSR, Cycles = 6 });
        instructions.Add(0x57, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });
        instructions.Add(0x58, new Instruction() { Name = "CLI", AddrMode = IMP, Operation = CLI, Cycles = 2 });
        instructions.Add(0x59, new Instruction() { Name = "EOR", AddrMode = ABY, Operation = EOR, Cycles = 4 });
        instructions.Add(0x5A, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 2 });
        instructions.Add(0x5B, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 7 });
        instructions.Add(0x5C, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 4 });
        instructions.Add(0x5D, new Instruction() { Name = "EOR", AddrMode = ABX, Operation = EOR, Cycles = 4 });
        instructions.Add(0x5E, new Instruction() { Name = "LSR", AddrMode = ABX, Operation = LSR, Cycles = 7 });
        instructions.Add(0x5F, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 7 });

        instructions.Add(0x60, new Instruction() { Name = "RTS", AddrMode = IMP, Operation = RTS, Cycles = 6 });
        instructions.Add(0x61, new Instruction() { Name = "ADC", AddrMode = IZX, Operation = ADC, Cycles = 6 });
        instructions.Add(0x62, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x63, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 8 });
        instructions.Add(0x64, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 3 });
        instructions.Add(0x65, new Instruction() { Name = "ADC", AddrMode = ZP0, Operation = ADC, Cycles = 3 });
        instructions.Add(0x66, new Instruction() { Name = "ROR", AddrMode = ZP0, Operation = ROR, Cycles = 5 });
        instructions.Add(0x67, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 5 });
        instructions.Add(0x68, new Instruction() { Name = "PLA", AddrMode = IMP, Operation = PLA, Cycles = 4 });
        instructions.Add(0x69, new Instruction() { Name = "ADC", AddrMode = IMM, Operation = ADC, Cycles = 2 });
        instructions.Add(0x6A, new Instruction() { Name = "ROR", AddrMode = IMP, Operation = ROR, Cycles = 2 });
        instructions.Add(0x6B, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x6C, new Instruction() { Name = "JMP", AddrMode = IND, Operation = JMP, Cycles = 5 });
        instructions.Add(0x6D, new Instruction() { Name = "ADC", AddrMode = ABS, Operation = ADC, Cycles = 4 });
        instructions.Add(0x6E, new Instruction() { Name = "ROR", AddrMode = ABS, Operation = ROR, Cycles = 6 });
        instructions.Add(0x6F, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });

        instructions.Add(0x70, new Instruction() { Name = "BVS", AddrMode = REL, Operation = BVS, Cycles = 2 });
        instructions.Add(0x71, new Instruction() { Name = "ADC", AddrMode = IZY, Operation = ADC, Cycles = 5 });
        instructions.Add(0x72, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x73, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 8 });
        instructions.Add(0x74, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 4 });
        instructions.Add(0x75, new Instruction() { Name = "ADC", AddrMode = ZPX, Operation = ADC, Cycles = 4 });
        instructions.Add(0x76, new Instruction() { Name = "ROR", AddrMode = ZPX, Operation = ROR, Cycles = 6 });
        instructions.Add(0x77, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });
        instructions.Add(0x78, new Instruction() { Name = "SEI", AddrMode = IMP, Operation = SEI, Cycles = 2 });
        instructions.Add(0x79, new Instruction() { Name = "ADC", AddrMode = ABY, Operation = ADC, Cycles = 4 });
        instructions.Add(0x7A, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 2 });
        instructions.Add(0x7B, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 7 });
        instructions.Add(0x7C, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 4 });
        instructions.Add(0x7D, new Instruction() { Name = "ADC", AddrMode = ABX, Operation = ADC, Cycles = 4 });
        instructions.Add(0x7E, new Instruction() { Name = "ROR", AddrMode = ABX, Operation = ROR, Cycles = 7 });
        instructions.Add(0x7F, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 7 });

        instructions.Add(0x80, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 2 });
        instructions.Add(0x81, new Instruction() { Name = "STA", AddrMode = IZX, Operation = STA, Cycles = 6 });
        instructions.Add(0x82, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 2 });
        instructions.Add(0x83, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });
        instructions.Add(0x84, new Instruction() { Name = "STY", AddrMode = ZP0, Operation = STY, Cycles = 3 });
        instructions.Add(0x85, new Instruction() { Name = "STA", AddrMode = ZP0, Operation = STA, Cycles = 3 });
        instructions.Add(0x86, new Instruction() { Name = "STX", AddrMode = ZP0, Operation = STX, Cycles = 3 });
        instructions.Add(0x87, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 3 });
        instructions.Add(0x88, new Instruction() { Name = "DEY", AddrMode = IMP, Operation = DEY, Cycles = 2 });
        instructions.Add(0x89, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 2 });
        instructions.Add(0x8A, new Instruction() { Name = "TXA", AddrMode = IMP, Operation = TXA, Cycles = 2 });
        instructions.Add(0x8B, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x8C, new Instruction() { Name = "STY", AddrMode = ABS, Operation = STY, Cycles = 4 });
        instructions.Add(0x8D, new Instruction() { Name = "STA", AddrMode = ABS, Operation = STA, Cycles = 4 });
        instructions.Add(0x8E, new Instruction() { Name = "STX", AddrMode = ABS, Operation = STX, Cycles = 4 });
        instructions.Add(0x8F, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 4 });

        instructions.Add(0x90, new Instruction() { Name = "BCC", AddrMode = REL, Operation = BCC, Cycles = 2 });
        instructions.Add(0x91, new Instruction() { Name = "STA", AddrMode = IZY, Operation = STA, Cycles = 6 });
        instructions.Add(0x92, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0x93, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });
        instructions.Add(0x94, new Instruction() { Name = "STY", AddrMode = ZPX, Operation = STY, Cycles = 4 });
        instructions.Add(0x95, new Instruction() { Name = "STA", AddrMode = ZPX, Operation = STA, Cycles = 4 });
        instructions.Add(0x96, new Instruction() { Name = "STX", AddrMode = ZPY, Operation = STX, Cycles = 4 });
        instructions.Add(0x97, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 4 });
        instructions.Add(0x98, new Instruction() { Name = "TYA", AddrMode = IMP, Operation = TYA, Cycles = 2 });
        instructions.Add(0x99, new Instruction() { Name = "STA", AddrMode = ABY, Operation = STA, Cycles = 5 });
        instructions.Add(0x9A, new Instruction() { Name = "TXS", AddrMode = IMP, Operation = TXS, Cycles = 2 });
        instructions.Add(0x9B, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 5 });
        instructions.Add(0x9C, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 5 });
        instructions.Add(0x9D, new Instruction() { Name = "STA", AddrMode = ABX, Operation = STA, Cycles = 5 });
        instructions.Add(0x9E, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 5 });
        instructions.Add(0x9F, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 5 });

        instructions.Add(0xA0, new Instruction() { Name = "LDY", AddrMode = IMM, Operation = LDY, Cycles = 2 });
        instructions.Add(0xA1, new Instruction() { Name = "LDA", AddrMode = IZX, Operation = LDA, Cycles = 6 });
        instructions.Add(0xA2, new Instruction() { Name = "LDX", AddrMode = IMM, Operation = LDX, Cycles = 2 });
        instructions.Add(0xA3, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });
        instructions.Add(0xA4, new Instruction() { Name = "LDY", AddrMode = ZP0, Operation = LDY, Cycles = 3 });
        instructions.Add(0xA5, new Instruction() { Name = "LDA", AddrMode = ZP0, Operation = LDA, Cycles = 3 });
        instructions.Add(0xA6, new Instruction() { Name = "LDX", AddrMode = ZP0, Operation = LDX, Cycles = 3 });
        instructions.Add(0xA7, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 3 });
        instructions.Add(0xA8, new Instruction() { Name = "TAY", AddrMode = IMP, Operation = TAY, Cycles = 2 });
        instructions.Add(0xA9, new Instruction() { Name = "LDA", AddrMode = IMM, Operation = LDA, Cycles = 2 });
        instructions.Add(0xAA, new Instruction() { Name = "TAX", AddrMode = IMP, Operation = TAX, Cycles = 2 });
        instructions.Add(0xAB, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0xAC, new Instruction() { Name = "LDY", AddrMode = ABS, Operation = LDY, Cycles = 4 });
        instructions.Add(0xAD, new Instruction() { Name = "LDA", AddrMode = ABS, Operation = LDA, Cycles = 4 });
        instructions.Add(0xAE, new Instruction() { Name = "LDX", AddrMode = ABS, Operation = LDX, Cycles = 4 });
        instructions.Add(0xAF, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 4 });

        instructions.Add(0xB0, new Instruction() { Name = "BCS", AddrMode = REL, Operation = BCS, Cycles = 2 });
        instructions.Add(0xB1, new Instruction() { Name = "LDA", AddrMode = IZY, Operation = LDA, Cycles = 5 });
        instructions.Add(0xB2, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0xB3, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 5 });
        instructions.Add(0xB4, new Instruction() { Name = "LDY", AddrMode = ZPX, Operation = LDY, Cycles = 4 });
        instructions.Add(0xB5, new Instruction() { Name = "LDA", AddrMode = ZPX, Operation = LDA, Cycles = 4 });
        instructions.Add(0xB6, new Instruction() { Name = "LDX", AddrMode = ZPY, Operation = LDX, Cycles = 4 });
        instructions.Add(0xB7, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 4 });
        instructions.Add(0xB8, new Instruction() { Name = "CLV", AddrMode = IMP, Operation = CLV, Cycles = 2 });
        instructions.Add(0xB9, new Instruction() { Name = "LDA", AddrMode = ABY, Operation = LDA, Cycles = 4 });
        instructions.Add(0xBA, new Instruction() { Name = "TSX", AddrMode = IMP, Operation = TSX, Cycles = 2 });
        instructions.Add(0xBB, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 4 });
        instructions.Add(0xBC, new Instruction() { Name = "LDY", AddrMode = ABX, Operation = LDY, Cycles = 4 });
        instructions.Add(0xBD, new Instruction() { Name = "LDA", AddrMode = ABX, Operation = LDA, Cycles = 4 });
        instructions.Add(0xBE, new Instruction() { Name = "LDX", AddrMode = ABY, Operation = LDX, Cycles = 4 });
        instructions.Add(0xBF, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 4 });

        instructions.Add(0xC0, new Instruction() { Name = "CPY", AddrMode = IMM, Operation = CPY, Cycles = 2 });
        instructions.Add(0xC1, new Instruction() { Name = "CMP", AddrMode = IZX, Operation = CMP, Cycles = 6 });
        instructions.Add(0xC2, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 2 });
        instructions.Add(0xC3, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 8 });
        instructions.Add(0xC4, new Instruction() { Name = "CPY", AddrMode = ZP0, Operation = CPY, Cycles = 3 });
        instructions.Add(0xC5, new Instruction() { Name = "CMP", AddrMode = ZP0, Operation = CMP, Cycles = 3 });
        instructions.Add(0xC6, new Instruction() { Name = "DEC", AddrMode = ZP0, Operation = DEC, Cycles = 5 });
        instructions.Add(0xC7, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 5 });
        instructions.Add(0xC8, new Instruction() { Name = "INY", AddrMode = IMP, Operation = INY, Cycles = 2 });
        instructions.Add(0xC9, new Instruction() { Name = "CMP", AddrMode = IMM, Operation = CMP, Cycles = 2 });
        instructions.Add(0xCA, new Instruction() { Name = "DEX", AddrMode = IMP, Operation = DEX, Cycles = 2 });
        instructions.Add(0xCB, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0xCC, new Instruction() { Name = "CPY", AddrMode = ABS, Operation = CPY, Cycles = 4 });
        instructions.Add(0xCD, new Instruction() { Name = "CMP", AddrMode = ABS, Operation = CMP, Cycles = 4 });
        instructions.Add(0xCE, new Instruction() { Name = "DEC", AddrMode = ABS, Operation = DEC, Cycles = 6 });
        instructions.Add(0xCF, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });

        instructions.Add(0xD0, new Instruction() { Name = "BNE", AddrMode = REL, Operation = BNE, Cycles = 2 });
        instructions.Add(0xD1, new Instruction() { Name = "CMP", AddrMode = IZY, Operation = CMP, Cycles = 5 });
        instructions.Add(0xD2, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0xD3, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 8 });
        instructions.Add(0xD4, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 4 });
        instructions.Add(0xD5, new Instruction() { Name = "CMP", AddrMode = ZPX, Operation = CMP, Cycles = 4 });
        instructions.Add(0xD6, new Instruction() { Name = "DEC", AddrMode = ZPX, Operation = DEC, Cycles = 6 });
        instructions.Add(0xD7, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });
        instructions.Add(0xD8, new Instruction() { Name = "CLD", AddrMode = IMP, Operation = CLD, Cycles = 2 });
        instructions.Add(0xD9, new Instruction() { Name = "CMP", AddrMode = ABY, Operation = CMP, Cycles = 4 });
        instructions.Add(0xDA, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 2 });
        instructions.Add(0xDB, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 7 });
        instructions.Add(0xDC, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 4 });
        instructions.Add(0xDD, new Instruction() { Name = "CMP", AddrMode = ABX, Operation = CMP, Cycles = 4 });
        instructions.Add(0xDE, new Instruction() { Name = "DEC", AddrMode = ABX, Operation = DEC, Cycles = 7 });
        instructions.Add(0xDF, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 7 });

        instructions.Add(0xE0, new Instruction() { Name = "CPX", AddrMode = IMM, Operation = CPX, Cycles = 2 });
        instructions.Add(0xE1, new Instruction() { Name = "SBC", AddrMode = IZX, Operation = SBC, Cycles = 6 });
        instructions.Add(0xE2, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 2 });
        instructions.Add(0xE3, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 8 });
        instructions.Add(0xE4, new Instruction() { Name = "CPX", AddrMode = ZP0, Operation = CPX, Cycles = 3 });
        instructions.Add(0xE5, new Instruction() { Name = "SBC", AddrMode = ZP0, Operation = SBC, Cycles = 3 });
        instructions.Add(0xE6, new Instruction() { Name = "INC", AddrMode = ZP0, Operation = INC, Cycles = 5 });
        instructions.Add(0xE7, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 5 });
        instructions.Add(0xE8, new Instruction() { Name = "INX", AddrMode = IMP, Operation = INX, Cycles = 2 });
        instructions.Add(0xE9, new Instruction() { Name = "SBC", AddrMode = IMM, Operation = SBC, Cycles = 2 });
        instructions.Add(0xEA, new Instruction() { Name = "NOP", AddrMode = IMP, Operation = NOP, Cycles = 2 });
        instructions.Add(0xEB, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0xEC, new Instruction() { Name = "CPX", AddrMode = ABS, Operation = CPX, Cycles = 4 });
        instructions.Add(0xED, new Instruction() { Name = "SBC", AddrMode = ABS, Operation = SBC, Cycles = 4 });
        instructions.Add(0xEE, new Instruction() { Name = "INC", AddrMode = ABS, Operation = INC, Cycles = 6 });
        instructions.Add(0xEF, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });

        instructions.Add(0xF0, new Instruction() { Name = "BEQ", AddrMode = REL, Operation = BEQ, Cycles = 2 });
        instructions.Add(0xF1, new Instruction() { Name = "SBC", AddrMode = IZY, Operation = SBC, Cycles = 5 });
        instructions.Add(0xF2, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 2 });
        instructions.Add(0xF3, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 8 });
        instructions.Add(0xF4, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 4 });
        instructions.Add(0xF5, new Instruction() { Name = "SBC", AddrMode = ZPX, Operation = SBC, Cycles = 4 });
        instructions.Add(0xF6, new Instruction() { Name = "INC", AddrMode = ZPX, Operation = INC, Cycles = 6 });
        instructions.Add(0xF7, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 6 });
        instructions.Add(0xF8, new Instruction() { Name = "SED", AddrMode = IMP, Operation = SED, Cycles = 2 });
        instructions.Add(0xF9, new Instruction() { Name = "SBC", AddrMode = ABY, Operation = SBC, Cycles = 4 });
        instructions.Add(0xFA, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 2 });
        instructions.Add(0xFB, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 7 });
        instructions.Add(0xFC, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = NOP, Cycles = 4 });
        instructions.Add(0xFD, new Instruction() { Name = "SBC", AddrMode = ABX, Operation = SBC, Cycles = 4 });
        instructions.Add(0xFE, new Instruction() { Name = "INC", AddrMode = ABX, Operation = INC, Cycles = 7 });
        instructions.Add(0xFF, new Instruction() { Name = "XXX", AddrMode = IMP, Operation = XXX, Cycles = 7 });
    }
}